import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import DashoardSidebar from '../components/DashoardSidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Zep Salad',
    description: 'Generated by create next app',
}

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className='w-[1240px] mx-auto flex gap-5 text-secondary'>
            <DashoardSidebar />
            <div className='w-7/12 mt-6'>
                {children}
            </div>
        </div>
    )
}